# Generated by Django 4.2.7 on 2023-11-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='usernames',
            field=models.TextField(default=''),
        ),
    ]
