# Generated by Django 4.2.7 on 2023-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mars', '0002_room_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='vacany',
            field=models.BooleanField(default=True),
        ),
    ]
