from sympy import Symbol, Derivative
print('Instructions - ')
print('For any two terms in multiplication enter * between them, eg. - 4x = 4*x')
print()
print('For power symbol use - **, eg - 4x^2 = 4*x**2')
print()
print('For trigonometric ratio put angle in (), eg - sinx = sin(x)')
print()
print('For underoot use a power of 0.5')
print()
print('This program cannot perform operations on log, cosec function and cot function')
x = Symbol(input('Enter the variable of equation - '))
equation = str(input('Enter Equation: '))
derivative= Derivative(equation, x)
result = derivative.doit()
print('\n\tYour Answer Is : ', result , '\n')
v = input('Press enter to quit! Thanks for using')